import { Octokit } from "octokit";
import { env } from "@/lib/env";

export type RepoFile = {
  path: string;
  /** UTF-8 text content, or base64 when `encoding === "base64"`. */
  content: string;
  encoding?: "utf-8" | "base64";
  /** Git file mode; defaults to 100644. Use 100755 for executables (gradlew). */
  mode?: "100644" | "100755";
};

export function adminOctokit(): Octokit {
  return new Octokit({ auth: env().GITHUB_ADMIN_TOKEN });
}

export function userOctokit(token: string): Octokit {
  return new Octokit({ auth: token });
}

export function org(): string {
  return env().GITHUB_ORG;
}

export function repoUrl(name: string): string {
  return `https://github.com/${org()}/${name}`;
}

/** Splits "org/name" → name. Accepts bare names too. */
export function repoName(fullName: string): string {
  return fullName.includes("/") ? fullName.split("/")[1] : fullName;
}

/** Invite the user to the org if they are not a member yet. Errors are ignored. */
export async function ensureOrgMember(login: string): Promise<void> {
  try {
    const gh = adminOctokit();
    try {
      await gh.rest.orgs.checkMembershipForUser({ org: org(), username: login });
      return;
    } catch {
      /* not a member */
    }
    await gh.rest.orgs.setMembershipForUser({ org: org(), username: login, role: "member" });
  } catch (e) {
    console.warn(`ensureOrgMember(${login}) failed:`, (e as Error).message);
  }
}

async function pushTree(
  gh: Octokit,
  owner: string,
  repo: string,
  branch: string,
  files: RepoFile[],
  message: string,
  baseSha?: string,
): Promise<string> {
  const blobs = await Promise.all(
    files.map(async (f) => {
      const { data } = await gh.rest.git.createBlob({
        owner,
        repo,
        content: f.content,
        encoding: f.encoding ?? "utf-8",
      });
      return { path: f.path, mode: f.mode ?? "100644", type: "blob" as const, sha: data.sha };
    }),
  );
  let baseTree: string | undefined;
  if (baseSha) {
    const { data: commit } = await gh.rest.git.getCommit({ owner, repo, commit_sha: baseSha });
    baseTree = commit.tree.sha;
  }
  const { data: tree } = await gh.rest.git.createTree({
    owner,
    repo,
    tree: blobs,
    base_tree: baseTree,
  });
  const { data: commit } = await gh.rest.git.createCommit({
    owner,
    repo,
    message,
    tree: tree.sha,
    parents: baseSha ? [baseSha] : [],
  });
  await gh.rest.git.updateRef({ owner, repo, ref: `heads/${branch}`, sha: commit.sha, force: false });
  return commit.sha;
}

/**
 * Create a public repo in the org, push all files as one commit on `main`,
 * and add the owner as an admin collaborator.
 */
export async function createRepoWithFiles(
  slug: string,
  description: string,
  files: RepoFile[],
  ownerLogin: string,
): Promise<{ fullName: string; htmlUrl: string; defaultBranch: string }> {
  const gh = adminOctokit();
  const owner = org();
  const { data: repo } = await gh.rest.repos.createInOrg({
    org: owner,
    name: slug,
    description: description.slice(0, 300),
    private: false,
    auto_init: true,
    has_issues: true,
    has_wiki: false,
  });
  const branch = repo.default_branch || "main";

  // auto_init creates an initial commit asynchronously; wait until the ref exists.
  let baseSha: string | undefined;
  for (let i = 0; i < 10 && !baseSha; i++) {
    try {
      const { data: ref } = await gh.rest.git.getRef({ owner, repo: slug, ref: `heads/${branch}` });
      baseSha = ref.object.sha;
    } catch {
      await new Promise((r) => setTimeout(r, 1000));
    }
  }
  if (!baseSha) throw new Error("リポジトリの初期化に失敗しました");

  await pushTree(gh, owner, slug, branch, files, "Initial commit (generated by OpenAP AI)", baseSha);

  try {
    await gh.rest.repos.addCollaborator({ owner, repo: slug, username: ownerLogin, permission: "admin" });
  } catch (e) {
    console.warn(`addCollaborator(${ownerLogin}) failed:`, (e as Error).message);
  }

  return { fullName: repo.full_name, htmlUrl: repo.html_url, defaultBranch: branch };
}

/** Create a branch from `base`, commit `files`, and open a PR — using the user's token. */
export async function createBranchCommitAndPr(
  userToken: string,
  repo: string,
  base: string,
  branch: string,
  files: RepoFile[],
  title: string,
  body: string,
): Promise<{ number: number; htmlUrl: string }> {
  const gh = userOctokit(userToken);
  const owner = org();
  const { data: baseRef } = await gh.rest.git.getRef({ owner, repo, ref: `heads/${base}` });
  await gh.rest.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseRef.object.sha });
  await pushTree(gh, owner, repo, branch, files, title, baseRef.object.sha);
  const { data: pr } = await gh.rest.pulls.create({ owner, repo, title, body, head: branch, base });
  return { number: pr.number, htmlUrl: pr.html_url };
}

export type RepoSummary = {
  name: string;
  fullName: string;
  description: string | null;
  htmlUrl: string;
  updatedAt: string | null;
  stars: number;
  openIssues: number;
  defaultBranch: string;
  language: string | null;
};

export async function listOrgRepos(query?: string): Promise<RepoSummary[]> {
  const gh = adminOctokit();
  const repos = await gh.paginate(gh.rest.repos.listForOrg, {
    org: org(),
    per_page: 100,
    sort: "updated",
    type: "public",
  });
  const q = query?.trim().toLowerCase();
  return repos
    .filter((r) => !q || r.name.toLowerCase().includes(q) || (r.description ?? "").toLowerCase().includes(q))
    .map((r) => ({
      name: r.name,
      fullName: r.full_name,
      description: r.description ?? null,
      htmlUrl: r.html_url,
      updatedAt: r.updated_at ?? null,
      stars: r.stargazers_count ?? 0,
      openIssues: r.open_issues_count ?? 0,
      defaultBranch: r.default_branch ?? "main",
      language: r.language ?? null,
    }));
}

export async function getRepo(name: string) {
  const gh = adminOctokit();
  const { data } = await gh.rest.repos.get({ owner: org(), repo: name });
  return data;
}

export type TreeEntry = { name: string; path: string; type: "dir" | "file"; size?: number };

/** List a directory (path "" = root). */
export async function getRepoTree(name: string, path: string, ref?: string): Promise<TreeEntry[]> {
  const gh = adminOctokit();
  const { data } = await gh.rest.repos.getContent({ owner: org(), repo: name, path, ref });
  if (!Array.isArray(data)) throw new Error("ディレクトリではありません");
  return data
    .map((e) => ({
      name: e.name,
      path: e.path,
      type: e.type === "dir" ? ("dir" as const) : ("file" as const),
      size: e.size,
    }))
    .sort((a, b) => (a.type === b.type ? a.name.localeCompare(b.name) : a.type === "dir" ? -1 : 1));
}

export async function getFileContent(
  name: string,
  path: string,
  ref?: string,
): Promise<{ content: string; size: number; binary: boolean; htmlUrl: string | null }> {
  const gh = adminOctokit();
  const { data } = await gh.rest.repos.getContent({ owner: org(), repo: name, path, ref });
  if (Array.isArray(data) || data.type !== "file") throw new Error("ファイルではありません");
  const buf = Buffer.from(data.content ?? "", "base64");
  const binary = buf.subarray(0, 8000).includes(0);
  return { content: binary ? "" : buf.toString("utf-8"), size: data.size, binary, htmlUrl: data.html_url };
}

/** Recursively fetch every text file in the repo (used for AI modification). */
export async function getAllTextFiles(name: string, ref?: string, maxBytes = 400_000): Promise<RepoFile[]> {
  const gh = adminOctokit();
  const owner = org();
  const branch = ref ?? (await getRepo(name)).default_branch;
  const { data: refData } = await gh.rest.git.getRef({ owner, repo: name, ref: `heads/${branch}` });
  const { data: tree } = await gh.rest.git.getTree({ owner, repo: name, tree_sha: refData.object.sha, recursive: "1" });
  const out: RepoFile[] = [];
  let total = 0;
  for (const item of tree.tree) {
    if (item.type !== "blob" || !item.path || !item.sha) continue;
    if (/\.(jar|png|jpg|jpeg|webp|gif|ico|zip|apk|so|ttf|otf)$/i.test(item.path)) continue;
    if ((item.size ?? 0) > 60_000) continue;
    const { data: blob } = await gh.rest.git.getBlob({ owner, repo: name, file_sha: item.sha });
    const text = Buffer.from(blob.content, "base64").toString("utf-8");
    if (text.includes(" ")) continue;
    total += text.length;
    if (total > maxBytes) break;
    out.push({ path: item.path, content: text });
  }
  return out;
}

export async function getReadme(name: string): Promise<string | null> {
  try {
    const gh = adminOctokit();
    const { data } = await gh.rest.repos.getReadme({ owner: org(), repo: name });
    return Buffer.from(data.content, "base64").toString("utf-8");
  } catch {
    return null;
  }
}

export async function listPulls(name: string, state: "open" | "closed" | "all" = "open") {
  const gh = adminOctokit();
  const { data } = await gh.rest.pulls.list({ owner: org(), repo: name, state, per_page: 50 });
  return data;
}

export async function getPull(name: string, number: number) {
  const gh = adminOctokit();
  const { data } = await gh.rest.pulls.get({ owner: org(), repo: name, pull_number: number });
  return data;
}

export async function getPullFiles(name: string, number: number) {
  const gh = adminOctokit();
  const { data } = await gh.rest.pulls.listFiles({ owner: org(), repo: name, pull_number: number, per_page: 100 });
  return data;
}

export async function listPullReviews(name: string, number: number) {
  const gh = adminOctokit();
  const { data } = await gh.rest.pulls.listReviews({ owner: org(), repo: name, pull_number: number });
  return data;
}

export async function listIssueComments(name: string, number: number) {
  const gh = adminOctokit();
  const { data } = await gh.rest.issues.listComments({ owner: org(), repo: name, issue_number: number, per_page: 100 });
  return data;
}

export async function mergePull(userToken: string, name: string, number: number) {
  const gh = userOctokit(userToken);
  const { data } = await gh.rest.pulls.merge({ owner: org(), repo: name, pull_number: number, merge_method: "squash" });
  return data;
}

export async function createReview(
  userToken: string,
  name: string,
  number: number,
  event: "APPROVE" | "REQUEST_CHANGES" | "COMMENT",
  body: string,
) {
  const gh = userOctokit(userToken);
  const { data } = await gh.rest.pulls.createReview({
    owner: org(),
    repo: name,
    pull_number: number,
    event,
    body: body || undefined,
  });
  return data;
}

export async function listIssues(name: string, state: "open" | "closed" | "all" = "open") {
  const gh = adminOctokit();
  const { data } = await gh.rest.issues.listForRepo({ owner: org(), repo: name, state, per_page: 50 });
  return data.filter((i) => !i.pull_request);
}

export async function createIssue(userToken: string, name: string, title: string, body: string) {
  const gh = userOctokit(userToken);
  const { data } = await gh.rest.issues.create({ owner: org(), repo: name, title, body });
  return data;
}

export async function listReleases(name: string) {
  const gh = adminOctokit();
  const { data } = await gh.rest.repos.listReleases({ owner: org(), repo: name, per_page: 30 });
  return data;
}

/** Create a tag on the default branch head and a GitHub Release for it. */
export async function createRelease(
  token: string,
  name: string,
  tag: string,
  releaseName?: string,
  body?: string,
) {
  const gh = userOctokit(token);
  const owner = org();
  const repo = await getRepo(name);
  const { data: ref } = await gh.rest.git.getRef({ owner, repo: name, ref: `heads/${repo.default_branch}` });
  try {
    await gh.rest.git.createRef({ owner, repo: name, ref: `refs/tags/${tag}`, sha: ref.object.sha });
  } catch (e) {
    const status = (e as { status?: number }).status;
    if (status !== 422) throw e; // 422 = tag already exists
  }
  const { data } = await gh.rest.repos.createRelease({
    owner,
    repo: name,
    tag_name: tag,
    name: releaseName || tag,
    body: body || "",
    draft: false,
    prerelease: false,
  });
  return data;
}

export async function listWorkflowRuns(name: string) {
  const gh = adminOctokit();
  const { data } = await gh.rest.actions.listWorkflowRunsForRepo({ owner: org(), repo: name, per_page: 10 });
  return data.workflow_runs;
}
